In [1]:
pip install tensorflow


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import tensorflow as tf
import numpy as np

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
## Setences 
sent = ['the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good']


In [7]:
## Defin the vocabulary size
vocab_size = 10000
## One hot representation
onehot_repr = [one_hot(words,vocab_size) for words in sent]
print(onehot_repr)

[[7948, 7999, 8886, 4338], [7948, 7999, 8886, 2155], [7948, 9176, 8886, 4118], [3890, 1230, 6999, 2666, 9295], [3890, 1230, 6999, 2666, 1428], [5315, 7948, 463, 8886, 9435], [6805, 1987, 8468, 2666]]


In [8]:
onehot_repr

[[7948, 7999, 8886, 4338],
 [7948, 7999, 8886, 2155],
 [7948, 9176, 8886, 4118],
 [3890, 1230, 6999, 2666, 9295],
 [3890, 1230, 6999, 2666, 1428],
 [5315, 7948, 463, 8886, 9435],
 [6805, 1987, 8468, 2666]]

In [9]:
# Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Embedding, Flatten


In [10]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7948 7999 8886 4338]
 [   0    0    0    0 7948 7999 8886 2155]
 [   0    0    0    0 7948 9176 8886 4118]
 [   0    0    0 3890 1230 6999 2666 9295]
 [   0    0    0 3890 1230 6999 2666 1428]
 [   0    0    0 5315 7948  463 8886 9435]
 [   0    0    0    0 6805 1987 8468 2666]]


In [11]:
## Feature representation
embedding_vector_features = 10
model = Sequential()
model.add(Embedding(vocab_size,embedding_vector_features,input_length=sent_length))
model.compile('adam','mse')

C:\Users\abcde\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7948, 7999, 8886, 4338])

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 374ms/step


array([[[-0.03703034, -0.02573617,  0.02210415,  0.03003687,
          0.03004918,  0.00258185, -0.03069384, -0.02059245,
         -0.04027193, -0.0317071 ],
        [-0.03703034, -0.02573617,  0.02210415,  0.03003687,
          0.03004918,  0.00258185, -0.03069384, -0.02059245,
         -0.04027193, -0.0317071 ],
        [-0.03703034, -0.02573617,  0.02210415,  0.03003687,
          0.03004918,  0.00258185, -0.03069384, -0.02059245,
         -0.04027193, -0.0317071 ],
        [-0.03703034, -0.02573617,  0.02210415,  0.03003687,
          0.03004918,  0.00258185, -0.03069384, -0.02059245,
         -0.04027193, -0.0317071 ],
        [ 0.00609369, -0.04163704, -0.0432124 , -0.04835493,
         -0.03664433, -0.00322568,  0.0346309 , -0.03278437,
         -0.02486088, -0.01143651],
        [ 0.02607169, -0.01256858,  0.00360627, -0.0340293 ,
         -0.04639433,  0.01517142, -0.03519074, -0.01205186,
          0.02074223,  0.02428177],
        [-0.00626975, -0.0255417 , -0.0031038 , -0.0